Improvements, docs, and a bugfix
canonical/cassandra-k8s-operator pull request #11
Opened 2021-06-02 19:33 UTC by dstathis

2021-06-02 19:46 UTC, rbarry82 reviewed
LGTM

2021-06-02 19:46 UTC, rbarry82 approved these changes

2021-06-02 20:31 UTC, sed-i requested changes
add `k8s` to `lib/charms` residents

2021-06-03 09:55 UTC, balbirthomas approved these changes

2021-06-03 20:06 UTC, sed-i approved these changes

2021-06-03 20:07 UTC, merged