Make Cassandra heap size configurable
canonical/cassandra-k8s-operator pull request #34
Opened 2021-08-02 10:11 UTC by mmanciop

Currently the Cassandra charm will always use the default heap-size hard-coded in the Cassandra startup scripts.

This change introduces the `heap_size` configuration, which accepts a valid JVM memory size, and passes it to the Cassandra bootstrap over the `JVM_OPTS` environment variable.

2021-08-02 10:17 UTC, balbirthomas approved these changes

2021-08-02 10:17 UTC, balbirthomas commented on src/charm.py
> +        if match("^\\d+[kKmMgG]$", heap_size) is None:
If you want to allow floating point values shouldn't the regular expression be something like `\d+(\.\d*)` . Also if you use raw strings then backslashes will not need to be escaped.

Nitpick: strictly speaking lower case "k" "m" and "g" are not standard memory sizes.

2021-08-02 13:51 UTC, jnsgruk commented on src/charm.py
> +        if match("^\\d+[kKmMgG]$", heap_size) is None:
Yeh, I'd expect `G`, `M`, `K` or `GiB`, `MiB` etc.

2021-08-02 13:54 UTC, jnsgruk commented on src/charm.py
> +        if match("^\\d+[kKmMgG]$", heap_size) is None:
I think (reading the doc string above) that the intention is to explicitly not support decimal/float value here.

```suggestion
        if match(r"^\d+[KMG]$", heap_size) is None:
```

2021-08-02 13:57 UTC, jnsgruk requested changes

2021-08-02 13:57 UTC, jnsgruk commented on tests/test_charm.py
> +    def test_heap_size_config_invalid(self, mock_net_get, mock_list_files):
I'd expect another test here showing that a valid memory config results in the relevant environment variable being present and correct in the pebble layer

2021-08-03 15:48 UTC, mmanciop commented on src/charm.py
> +        if match("^\\d+[kKmMgG]$", heap_size) is None:
@balbirthomas the JVM accepts only integers. That is why I am testing for failure with `0.5g` :-)

2021-08-04 08:11 UTC, jnsgruk requested changes

2021-08-04 08:11 UTC, jnsgruk commented on config.yaml
> +      `k` (Kylobytes), `m` (megabytes), `g` (gigabytes).
Need to remove the lower case equivalents here now :)

2021-08-04 08:11 UTC, jnsgruk commented on tests/test_charm.py
> +        self.harness.update_config({"heap_size": "1g"})
This test should fail and put the charm into `BlockedStatus` no? (lower case unit)

2021-08-05 07:51 UTC, mmanciop commented on config.yaml
> +      `k` (Kylobytes), `m` (megabytes), `g` (gigabytes).
Why? They are still valid values for the config.

2021-08-05 07:53 UTC, mmanciop commented on tests/test_charm.py
> +        self.harness.update_config({"heap_size": "1g"})
Nope `1g` is a perfectly valid JVM memory value

2021-08-05 08:03 UTC, jnsgruk approved these changes

2021-08-05 11:38 UTC, merged