Rewrite Draft
canonical/cassandra-k8s-operator pull request #42
Opened 2021-08-30 17:57 UTC by dstathis

2021-09-10 12:17 UTC, jnsgruk commented on CONTRIBUTING.md
> +charmcraft build
```suggestion
charmcraft pack
```

2021-09-10 12:17 UTC, jnsgruk commented on CONTRIBUTING.md
> +The Python operator framework includes a very nice harness for testing operator
```suggestion
The Charmed Operator Framework includes a very nice harness for testing operator
```

2021-09-10 12:17 UTC, jnsgruk commented on .github/workflows/run_tests.yaml
> +# Copyright 2020 Canonical Ltd.
```suggestion
# Copyright 2021 Canonical Ltd.
```

Applies throughout project.

2021-09-10 12:28 UTC, jnsgruk commented
Had a few minutes so have updated the tox and pyproject config

2021-09-15 18:12 UTC, dstathis commented
Fixes #37

2021-10-20 21:36 UTC, dstathis commented
This is not the final version of the Cassandra rewrite but I think it is a good checkpoint with lots of improvements

2021-10-20 21:37 UTC, dstathis commented
Also, I am aware the integration tests are failing. This is a test failure and not a charm failure as it succeeds when run locally. I'm looking in to it but don't want to delay for this.

2021-10-20 21:39 UTC, dstathis commented
Fixes #32

2021-10-20 21:40 UTC, dstathis commented
Fixes #27

2021-10-21 07:55 UTC, mmanciop commented
@sed-i can you please have a look at the integration test?

2021-10-21 09:59 UTC, jnsgruk reviewed
Looking much better, a few comments :)

2021-10-21 09:59 UTC, jnsgruk commented on README.md
> +   [here](https://charmhub.io/prometheus-k8s/libraries/prometheus).
```suggestion
   [here](https://charmhub.io/prometheus-k8s/libraries/prometheus_scrape).
```

2021-10-21 09:59 UTC, jnsgruk commented on lib/charms/cassandra_k8s/v0/cassandra.py
> +"""# cassandra charm library.
```suggestion
"""# Cassandra charm library.
```

2021-10-21 09:59 UTC, jnsgruk commented on lib/charms/cassandra_k8s/v0/cassandra.py
> +
```suggestion
```

2021-10-21 09:59 UTC, jnsgruk commented on lib/charms/cassandra_k8s/v0/cassandra.py
> +
```suggestion
```

2021-10-21 09:59 UTC, jnsgruk commented on lib/charms/cassandra_k8s/v0/cassandra.py
> +
```suggestion
```

2021-10-21 09:59 UTC, jnsgruk commented on lib/charms/cassandra_k8s/v0/cassandra.py
> +
```suggestion
```

2021-10-21 09:59 UTC, jnsgruk commented on pyproject.toml
> +
```suggestion
```

I think in the case of charms, where we have `metadata.yaml`, this likely serves only to become out of sync and wrong ;)

2021-10-21 09:59 UTC, jnsgruk commented on src/cassandra_server.py
> +    def connect(
I wonder if this might be better named `session`?

```python
with self.session(event):
    # blah
```

2021-10-21 09:59 UTC, jnsgruk commented on src/cassandra_server.py
> +            self.charm.unit.status = MaintenanceStatus("Waiting for Database")
```suggestion
            self.charm.unit.status = MaintenanceStatus("Waiting for database")
```

Applies elsewhere too

2021-10-21 09:59 UTC, jnsgruk commented on src/charm.py
> +# We should remove it when the bug is fixed.
This is indeed now supported, so we can drop this :)

2021-10-21 09:59 UTC, jnsgruk commented on src/charm.py
> +    def on_pebble_ready(self, event: EventBase) -> None:
```suggestion
    def _on_pebble_ready(self, event: WorkloadEvent) -> None:
```

2021-10-21 09:59 UTC, jnsgruk commented on src/charm.py
> +        if self._num_units() != self._goal_units():
```suggestion
        if self._num_units() != self.app.planned_units():
```

feels like that `_goal_units` helper isn't providing a lot of value at this point

2021-10-21 09:59 UTC, jnsgruk commented on src/charm.py
> +            self.unit.status = MaintenanceStatus("Waiting for units")
This status message could be a little more helpful

2021-10-21 09:59 UTC, jnsgruk commented on src/charm.py
> +                return
Do we need some kind of logging/error/unit status here?

2021-10-21 09:59 UTC, jnsgruk commented on src/charm.py
> +        if len(self.model.relations["monitoring"]) > 0:
```suggestion
        if not self.model.relations["monitoring"]:
```

2021-10-21 09:59 UTC, jnsgruk commented on src/charm.py
> +    def on_config_changed(self, event: EventBase) -> None:
```suggestion
    def on_config_changed(self, event: ConfigChangedEvent) -> None:
```

2021-10-21 09:59 UTC, jnsgruk commented on src/charm.py
> +            self._container.get_plan().to_dict().get("services", {}).get("cassandra")
```suggestion
            "cassandra" in self._container.get_plan().services
```

I think the suggested would work (and be simpler), but needs confirming :)

2021-10-21 09:59 UTC, jnsgruk commented on src/charm.py
> +            if self._container.can_connect():
```suggestion
        if not self.model.relations["monitoring"] and self._container.can_connect():
```

2021-10-21 09:59 UTC, jnsgruk commented on src/charm.py
> +                return
Do we need to error/set a status here?

2021-10-21 09:59 UTC, jnsgruk commented on src/charm.py
> +                    return
As above?

2021-10-21 09:59 UTC, jnsgruk commented on src/charm.py
> +        services = self._container.get_plan().to_dict().get("services", {})
I think you can now do `self._container.get_plan().services` here and the comparison with the dict you construct will be correct (@rbarry82 added an `__eq__` somewhere in `ops`)

2021-10-21 09:59 UTC, jnsgruk commented on src/charm.py
>          conf = {
Feels like this could be a Python object that serialises to a dict? perhaps a dataclass in your `cassandra.py` that models the config better? (probably a "future work" thing)

2021-10-21 14:37 UTC, dstathis commented on README.md
> +   [here](https://charmhub.io/prometheus-k8s/libraries/prometheus).
Done.

2021-10-21 14:38 UTC, dstathis commented on lib/charms/cassandra_k8s/v0/cassandra.py
> +
Black doesn't like this.

2021-10-21 14:39 UTC, dstathis commented on lib/charms/cassandra_k8s/v0/cassandra.py
> +
Black doesn't like this.

2021-10-21 14:39 UTC, dstathis commented on lib/charms/cassandra_k8s/v0/cassandra.py
> +
Black doesn't like this.

2021-10-21 14:41 UTC, sed-i commented on README.md
> +## Integrations
iiuc, the "relations" header was for a brief mention and integrations.md was for in-depth. Are we doing something different now?

2021-10-21 14:41 UTC, sed-i commented on lib/charms/cassandra_k8s/v0/cassandra.py
>      pass
`pass` is redundant when you have a docstring.

2021-10-21 14:41 UTC, sed-i commented on lib/charms/cassandra_k8s/v0/cassandra.py
>      pass
`pass` is redundant when you have a docstring.

2021-10-21 14:41 UTC, sed-i commented on lib/charms/cassandra_k8s/v0/cassandra.py
>      pass
`pass` is redundant when you have a docstring.

2021-10-21 14:41 UTC, sed-i commented on lib/charms/cassandra_k8s/v0/cassandra.py
> +# Copyright 2020 Canonical Ltd.
File comment: based on metadata.yaml, seems like this lib should be renamed to cql.

2021-10-21 14:41 UTC, sed-i commented on lib/charms/cassandra_k8s/v0/cassandra.py
> +    """Cassandra consumer object."""
Goodies missing from docstring :D

2021-10-21 14:41 UTC, sed-i commented on lib/charms/cassandra_k8s/v0/cassandra.py
> +    def __init__(self, charm: CharmBase, name: str):
For your consideration:

We now add a default for relation names
https://github.com/canonical/alertmanager-operator/pull/39/files#diff-d010fdb885e58b37b0ff44c7a02d5338a1228977e0b974fa08b9cf29f7319f89

- defaults for relation name
- module wide "Final", INTERFACE_NAME
- validate_relation(relation_name, relation_role)

for both provider & consumer.

2021-10-21 14:41 UTC, sed-i commented on lib/charms/cassandra_k8s/v0/cassandra.py
> +        """Returns a dict of credentials.
dict or tuple?

2021-10-21 14:41 UTC, sed-i commented on lib/charms/cassandra_k8s/v0/cassandra.py
> +    def credentials(self, rel_id: Optional[int] = None) -> tuple:
`Optional` is redundant (inferred) when default is None

2021-10-21 14:41 UTC, sed-i commented on lib/charms/cassandra_k8s/v0/cassandra.py
>          {"username": <username>, "password": <password>}
I think a (named)tuple would do better service.

2021-10-21 14:41 UTC, sed-i commented on lib/charms/cassandra_k8s/v0/cassandra.py
> +    def databases(self, rel_id: Optional[int] = None) -> list:
`Optional` is redundant (inferred) when default is None
There are more occurrences.

2021-10-21 14:41 UTC, sed-i commented on lib/charms/cassandra_k8s/v0/cassandra.py
> +        db_name = f"juju_db_{sanitize_name(self.charm.model.name)}_{sanitize_name(self.charm.app.name)}{sanitize_name(name_suffix)}"
You may find this useful

```python
@dataclasses.dataclass(frozen=True)
class JujuTopology:
```
Still WIP though.

https://github.com/canonical/prometheus-operator/pull/149/files#diff-3eb4f4fb71ab351956c8e7b96b07a804995e81540a0d2e94c2f63333c7792f79

2021-10-21 14:41 UTC, sed-i commented on src/cassandra_server.py
> +    pass
redundant

2021-10-21 14:41 UTC, sed-i commented on src/cassandra_server.py
> +"""Cassandra Server Object."""
Could you please elaborate?

2021-10-21 14:41 UTC, sed-i commented on src/cassandra_server.py
> +        self.charm = charm
This looks suspicious.
I also see below you're using defer etc.
I wonder this must be so tightly coupled with the charm and OF.

2021-10-21 14:41 UTC, sed-i commented on src/charm.py
> +        if self._set_config_file(event) is False:
```suggestion
        if not self._set_config_file(event):
```

2021-10-21 14:41 UTC, sed-i commented on src/charm.py
> +                return
I'd also appreciate some comments - it is difficult to tell what is the goal with all these checks etc.

2021-10-21 14:41 UTC, sed-i commented on src/charm.py
> +            self._container.get_plan().to_dict().get("services", {}).get("cassandra")
Yep looks right. I'm using the somewhat equivalent `if not self.container.get_plan().services.get(self._service_name):`

2021-10-21 14:41 UTC, sed-i commented on src/charm.py
> +        self.provider.update_address("database", self._hostname())
Nice

2021-10-21 14:45 UTC, sed-i commented on tests/integration/test_charm.py
>          f"{my_charm.parents[0]}/cassandra-k8s_ubuntu-20.04-amd64.charm",
```suggestion
        my_charm,
```

2021-10-21 14:47 UTC, sed-i commented on tests/integration/test_charm.py
>  #!/usr/bin/env python3
Consider relating to all relevant charms, and await status="active".

2021-10-21 14:50 UTC, sed-i commented
> @sed-i can you please have a look at the integration test?

The most recent failed test says `Unit in error: cassandra-k8s/0`, which means the charm's status was not idle/active but error.

2021-10-21 14:51 UTC, dstathis commented on src/cassandra_server.py
> +    def connect(
Any reason you prefer session here?

2021-10-21 14:59 UTC, dstathis commented on src/charm.py
> +# We should remove it when the bug is fixed.
No it isn't

```
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-cass-0/charm/venv/ops/model.py", line 1133, in restart
    self._pebble.restart_services(service_names)
  File "/var/lib/juju/agents/unit-cass-0/charm/venv/ops/pebble.py", line 1250, in restart_services
    return self._services_action('restart', services, timeout, delay)
  File "/var/lib/juju/agents/unit-cass-0/charm/venv/ops/pebble.py", line 1263, in _services_action
    resp = self._request('POST', '/v1/services', body=body)
  File "/var/lib/juju/agents/unit-cass-0/charm/venv/ops/pebble.py", line 1074, in _request
    response = self._request_raw(method, path, query, headers, data)
  File "/var/lib/juju/agents/unit-cass-0/charm/venv/ops/pebble.py", line 1114, in _request_raw
    raise APIError(body, code, status, message)
ops.pebble.APIError: action "restart" is unsupported
```

2021-10-21 15:02 UTC, dstathis commented on src/charm.py
> +    def on_pebble_ready(self, event: EventBase) -> None:
There are two suggestions here. The first seems to be to make this callback private. None of the others are and I would argue callbacks are by definition not private.

The second is a more specific type annotation. I was trying to be less specific with these to avoid too many imports. How do people feel about this in general?

2021-10-21 15:04 UTC, dstathis commented on src/charm.py
> +        if self._num_units() != self._goal_units():
I'll remove self._goal_units all together in the next PR.

2021-10-21 15:04 UTC, dstathis commented on src/charm.py
> +            self.unit.status = MaintenanceStatus("Waiting for units")
Could it? What would you suggest?

2021-10-21 15:07 UTC, dstathis commented on src/charm.py
> +                return
I agree it is kind of difficult to understand the error flow. A result of not using the much more pythonic concept of exceptions :). I'll add some comments.

2021-10-21 15:11 UTC, dstathis commented on src/charm.py
> +        if len(self.model.relations["monitoring"]) > 0:
The suggested change is backward so I will commit manually.

2021-10-21 15:12 UTC, sed-i commented on src/charm.py
> +# We should remove it when the bug is fixed.
I haven't tested yet myself, but maybe you need `tox ... --recreate`?

2021-10-21 15:13 UTC, dstathis commented on src/charm.py
> +    def on_config_changed(self, event: EventBase) -> None:
Se the similar suggestion to pebble_ready.

2021-10-21 15:17 UTC, sed-i commented on src/charm.py
> +    def on_pebble_ready(self, event: EventBase) -> None:
WorkloadEvent is correct and EventBase is technically wrong in this context.
I do not understand your comment about public callback: no one from outside this class is going to use this callback _directly_, i.e. the class inner logic can still pass it around as argument no problem.
In other words, I do think _on_pebble_ready makes sense as the equivalent of a `protected` filed in c++.

2021-10-21 15:21 UTC, dstathis commented on src/charm.py
> +            self._container.get_plan().to_dict().get("services", {}).get("cassandra")
Yup done.

2021-10-21 15:22 UTC, sed-i commented on src/charm.py
> +    def on_config_changed(self, event: EventBase) -> None:
The type hint should hint correctly... EventBase is only a subset of what ConfigChangedEvent has to offer.
It is technically wrong to use EventBase here.

2021-10-21 15:24 UTC, dstathis commented on src/charm.py
> +                return
No we already did in create_user(). I agree this is confusing. Another +1 for using exceptions. I'll put a comment.

2021-10-21 15:25 UTC, dstathis commented on src/charm.py
> +                    return
See above.

2021-10-21 15:29 UTC, dstathis commented on src/charm.py
>          conf = {
Could you elaborate? What would be the benefit?

2021-10-21 15:29 UTC, jnsgruk commented on lib/charms/cassandra_k8s/v0/cassandra.py
> +
Fair enough :)

2021-10-21 15:31 UTC, jnsgruk commented on src/cassandra_server.py
> +    def connect(
Yeh, just feels like it's used to get access to a session? Not a massive problem either way, but the language just makes it more obvious `with self.session():` vs `with self.connect():`

2021-10-21 15:31 UTC, dstathis commented on README.md
> +## Integrations
The in depth discussion happens in the charm lib docs anyway. I discussed merging the two docs at some point and if I recall correctly people agreed.

2021-10-21 15:32 UTC, jnsgruk commented on src/charm.py
> +# We should remove it when the bug is fixed.
Yeh, should be fixed in latest commits to `ops`

2021-10-21 15:34 UTC, jnsgruk commented on src/charm.py
> +    def on_pebble_ready(self, event: EventBase) -> None:
By convention, you callbacks should be private. It's how they are in the template, and in all of the other observability charms.

Making this a `WorkloadEvent` allows things like autocomplete/type checking to work out that this event carries a `workload` property, for example - so I think being more specific is better.

2021-10-21 15:36 UTC, jnsgruk commented on src/charm.py
> +    def on_config_changed(self, event: EventBase) -> None:
Agree with @sed-i

2021-10-21 15:48 UTC, dstathis commented on lib/charms/cassandra_k8s/v0/cassandra.py
>      pass
Done.

2021-10-21 16:08 UTC, jnsgruk commented on src/charm.py
> +                return
In general, I'd prefer if `event.defer` was more explicitly in the event callbacks, rather than hidden away in helper methods. Should only result in a minor refactor here, but I think it'll make it more readable for sure.

2021-10-21 16:14 UTC, dstathis commented on lib/charms/cassandra_k8s/v0/cassandra.py
>      pass
Done.

2021-10-21 16:14 UTC, dstathis commented on lib/charms/cassandra_k8s/v0/cassandra.py
>      pass
Done.

2021-10-21 16:15 UTC, dstathis commented on lib/charms/cassandra_k8s/v0/cassandra.py
> +# Copyright 2020 Canonical Ltd.
Yes which is unfortunately not easy. It requires getting special help from charmhub people. I will do this but not as part of this PR.

2021-10-21 16:16 UTC, dstathis commented on lib/charms/cassandra_k8s/v0/cassandra.py
> +    """Cassandra consumer object."""
Like what?

2021-10-21 16:17 UTC, dstathis commented on lib/charms/cassandra_k8s/v0/cassandra.py
> +    def __init__(self, charm: CharmBase, name: str):
Yup there is more work to be done here. This is not the last PR.

2021-10-21 16:20 UTC, sed-i commented on lib/charms/cassandra_k8s/v0/cassandra.py
> +    """Cassandra consumer object."""
o11y charms I've seen have context + usage examples
- https://github.com/canonical/prometheus-operator/blob/0f6c85222e78cd001585c2dd5315f5b21325e8ec/lib/charms/prometheus_k8s/v0/prometheus_scrape.py#L903
- https://github.com/canonical/grafana-operator/blob/7f731fd7c8af6e9fff78230d014d412b8fcab7e0/lib/charms/grafana_k8s/v0/grafana_source.py#L188
- https://github.com/canonical/loki-operator/blob/d6603b1028a8e9c9c2bb4f211d2c6282d6654460/lib/charms/loki_k8s/v0/loki_push_api.py#L635
- https://github.com/canonical/alertmanager-operator/blob/e3c1cb46a67225dfaf2c9e5c3a4d3c7ec3cc7e2a/lib/charms/alertmanager_k8s/v0/alertmanager_dispatch.py#L99

2021-10-21 16:22 UTC, sed-i commented on lib/charms/cassandra_k8s/v0/cassandra.py
> +    def __init__(self, charm: CharmBase, name: str):
Consider opening issues for deferred :D items

2021-10-21 16:26 UTC, dstathis commented on lib/charms/cassandra_k8s/v0/cassandra.py
> +        """Returns a dict of credentials.
Done.

2021-10-21 16:28 UTC, dstathis commented on src/cassandra_server.py
> +"""Cassandra Server Object."""
What would you like to know?

2021-10-21 16:28 UTC, dstathis commented on src/cassandra_server.py
> +        self.charm = charm
Because how else would it defer events?

2021-10-21 16:46 UTC, sed-i commented on src/cassandra_server.py
> +"""Cassandra Server Object."""
why this file exist, what the stuff inside does, what is the meaning of "server" in this context, what dependencies are there, ...

2021-10-21 16:47 UTC, sed-i commented on src/cassandra_server.py
> +        self.charm = charm
Maybe deferring should not be delegated here in the first place?

2021-10-21 18:24 UTC, dstathis commented
> > @sed-i can you please have a look at the integration test?
> 
> The most recent failed test says `Unit in error: cassandra-k8s/0`, which means the charm's status was not idle/active but error.

Yeah I see this and I haven't been able to figure out why. It always passes when run locally. Also, I briefly looked at some other repos and they seem to be having the same error.

2021-10-21 18:29 UTC, dstathis commented on lib/charms/cassandra_k8s/v0/cassandra.py
> +    def __init__(self, charm: CharmBase, name: str):
This is all part of the rewrite from the feedback I got. There is a lot of it and I am still in the process of rewriting. This is simply a checkpoint to cut an edge release. I don't think opening a ton of issues makes sense.

2021-10-21 18:31 UTC, sed-i commented
> Yeah I see this and I haven't been able to figure out why.

In your `[testenv:integration]`, change the command to
`pytest -v --tb native --log-cli-level=INFO -s {posargs} {toxinidir}/tests/integration`
and you will be able to see more log messages

2021-10-21 18:32 UTC, dstathis commented on src/cassandra_server.py
> +    def connect(
Hm, I see your point. I tend to model my context managers after `with open('filepath') as f: ...`. I think connect follows that pattern more so I prefer it. Feel free to veto me here as I don't feel strongly.

2021-10-21 18:34 UTC, dstathis commented on src/cassandra_server.py
> +            self.charm.unit.status = MaintenanceStatus("Waiting for Database")
@mmanciop Had mentioned that the standard is to do all lowercase. Which would be "waiting for database". It needs to be fixed in many places, and I plan on including that in the next PR.

2021-10-21 18:37 UTC, sed-i commented on lib/charms/cassandra_k8s/v0/cassandra.py
> +    def __init__(self, charm: CharmBase, name: str):
Makes sense. I personally find opening issues easier than remembering.

2021-10-21 18:40 UTC, dstathis commented on src/charm.py
> +# We should remove it when the bug is fixed.
I just rebuilt with a `charmcraft clean` first (tox is not involved) and the error remains. My understanding is this is a known bug in <em>pebble</em>.

2021-10-21 18:44 UTC, dstathis commented on src/charm.py
> +    def on_pebble_ready(self, event: EventBase) -> None:
I sort of viewed it as a callback being called by outside code so it should be public, but I can see how maybe this isn't completely the case.

I will change the callbacks to be private if you want, but, please first consider that literally every member of this class will be private. At that point it sort of seems like we are just adding underscores for no reason.

2021-10-21 18:48 UTC, dstathis commented on lib/charms/cassandra_k8s/v0/cassandra.py
> +    """Cassandra consumer object."""
Those docs do not show up in charmhub unless you put them at the top of the file. Are people duplicating their docs to exist at the top of the library and also in the constructor? If so, I think this requires some discussion. Navigating to github and opening source files should not be required to get at documentation.

2021-10-21 18:49 UTC, dstathis commented on lib/charms/cassandra_k8s/v0/cassandra.py
> +    def __init__(self, charm: CharmBase, name: str):
It's only because there is a large backlog that has my attention. In a normal situation, I would absolutely open an issue.

2021-10-21 21:04 UTC, sed-i commented on lib/charms/cassandra_k8s/v0/cassandra.py
> +    """Cassandra consumer object."""
Context + usage examples is what you expect to have in classes, and is what displayed by IDEs on demand.
Charmhub idiosyncrasies are orthogonal to proper doc style.

2021-10-21 22:34 UTC, dstathis commented on lib/charms/cassandra_k8s/v0/cassandra.py
> +        db_name = f"juju_db_{sanitize_name(self.charm.model.name)}_{sanitize_name(self.charm.app.name)}{sanitize_name(name_suffix)}"
I'd love to use this if it showed up in a library somewhere

2021-10-25 05:55 UTC, dstathis commented on src/charm.py
> +                return
Moved all defers to the top level methods.

2021-10-25 06:02 UTC, dstathis commented on src/charm.py
> +    def on_config_changed(self, event: EventBase) -> None:
Done.

2021-10-25 06:14 UTC, dstathis commented on lib/charms/cassandra_k8s/v0/cassandra.py
>          {"username": <username>, "password": <password>}
It's not a dict anymore anyway.

2021-10-25 06:16 UTC, dstathis commented on src/cassandra_server.py
> +        self.charm = charm
The defers are removed but I still use self.charm in a number of places. Is there still concern here. I don't really see any reason why these shouldn't be coupled as this is not a library.

2021-10-25 06:17 UTC, dstathis commented on src/charm.py
> +        if self._set_config_file(event) is False:
why?

2021-10-25 06:19 UTC, dstathis commented on tests/integration/test_charm.py
>  #!/usr/bin/env python3
I will for sure. Outside the scope of this PR though.

2021-10-25 09:40 UTC, jnsgruk commented on src/cassandra_server.py
> +    def connect(
Sure, that works

2021-10-25 09:40 UTC, jnsgruk commented on src/charm.py
> +# We should remove it when the bug is fixed.
Hmm. What version is your Juju controller?

2021-10-25 09:41 UTC, jnsgruk commented on src/charm.py
> +    def on_pebble_ready(self, event: EventBase) -> None:
No reason for that not to be the case, and that will make this consistent with the other charms maintained by your team/the data team in the future.

2021-10-25 09:45 UTC, jnsgruk commented on src/charm.py
>          conf = {
There are just quite a few hard-coded constant values in here. The alternative might allow something like:

```python
config = self.cassandra_provider.generate_config(option1=value, option2=value, ...)
# ...
self.container.push(CONFIG_PATH, config.to_yaml())
```

Which just seems a little tidier in your event handler (especially if your supported config options change in the future). I'm not hard over, just an observation.

2021-10-25 20:46 UTC, dstathis commented on src/charm.py
> +# We should remove it when the bug is fixed.
Looks like this was fixed with your commit today. Reverting.

2021-10-25 20:47 UTC, dstathis commented on src/charm.py
>          conf = {
I'll keep this in mind. Definitely out of scope for this PR but a good idea.

2021-10-25 20:48 UTC, dstathis commented on lib/charms/cassandra_k8s/v0/cassandra.py
> +    """Cassandra consumer object."""
I am going to leave as is for now but we should definitely discus this further before my next PR.

2021-10-25 20:49 UTC, dstathis commented on src/cassandra_server.py
> +"""Cassandra Server Object."""
Yeah this would definitely be useful. I'll include in the next PR when I do more doc work.

2021-10-29 04:01 UTC, sed-i approved these changes

2021-10-29 04:01 UTC, sed-i commented on lib/charms/cassandra_k8s/v0/cql.py
>          relation.data[self.charm.app]["requested_databases"] = json.dumps(requested_databases)
I didn't see a leader guard in the diff. Just making sure there is one somewhere.
FWIW, I try to place leader guards as close as possible to where they are needed.

2021-10-29 04:01 UTC, sed-i commented on lib/charms/cassandra_k8s/v0/cql.py
> +        """Return the list of requested databases.
Consider elaborating (requested by who and from who; what are the consequences).

2021-10-29 04:01 UTC, sed-i commented on lib/charms/cassandra_k8s/v0/cql.py
> +    def update_port(self, relation_name: str, port: int) -> None:
I saw you removed port from config so not sure why this is still needed.

2021-10-29 04:01 UTC, sed-i commented on lib/charms/cassandra_k8s/v0/cql.py
> +        """Update the address which Cassandra is listening on.
Can you elaborate why this is needed? i.e. when should this ever change.

2021-10-29 04:01 UTC, sed-i commented on src/cassandra_server.py
> +            yield session
What is the idea behind yield with only one iteration?

2021-10-29 04:01 UTC, sed-i commented on src/charm.py
>              return
else clause missing?

2021-10-29 04:01 UTC, sed-i commented on src/charm.py
> +        if not self.model.relations["monitoring"] and self._container.can_connect():
> `if not self.model.relations["monitoring"]`

not sure what is the effect of this condition:
1. we're already in `_broken` so we know the relation is being completely removed
2. iirc, even on `_broken` you may still see stuff in there because they are not yet "cleaned up"

2021-10-29 04:01 UTC, sed-i commented on src/charm.py
>              username = f"juju-user-{event.app_name}"
Do we need to worry here about the uniqueness of `event.app_name`?

2021-10-29 04:01 UTC, sed-i commented on src/charm.py
> +    def _hostname(self, unit_number: Optional[int] = None) -> str:
Optional is inferred when default is None

2021-10-29 04:01 UTC, sed-i commented on src/charm.py
> +        seeds_list = [self._hostname(unit_number=x) for x in [0, 1, 2]][: self._goal_units()]
Based on the code seems like the comment should say "of **at most** the first 3 units"
```suggestion
        # The seeds should be the hostnames of at most the first 3 units.
        seeds_list = list(map(self._hostname, range(min(self._goal_units(), 3))))
```

2021-10-29 04:01 UTC, sed-i commented on src/charm.py
> +                    raise
This part is a bit confusing.
Why not replace it all with 
```suggestion
            self._set_layer()
            self._container.restart("cassandra")
```

2021-10-29 04:01 UTC, sed-i commented on tox.ini
> +    pep8-naming
What about throwing codespell in?

2021-10-29 04:35 UTC, dstathis commented on lib/charms/cassandra_k8s/v0/cql.py
>          relation.data[self.charm.app]["requested_databases"] = json.dumps(requested_databases)
I don't have a leader guard in the consumer calls. It would seem wrong to return silently if not running as the leader. On the other hand only the leader can set app data. Perhaps raise an exception? Thoughts?

2021-10-29 04:37 UTC, dstathis commented on lib/charms/cassandra_k8s/v0/cql.py
> +    def update_port(self, relation_name: str, port: int) -> None:
Because this is a library. I have no idea what port the charm is using.

2021-10-29 04:39 UTC, dstathis commented on lib/charms/cassandra_k8s/v0/cql.py
> +        """Update the address which Cassandra is listening on.
Pod restart for example.

2021-10-29 04:40 UTC, dstathis commented on src/cassandra_server.py
> +            yield session
This is one way of defining context managers. See docs for `contextlib.contextmanager`.

2021-10-29 04:41 UTC, dstathis commented on src/charm.py
>              return
No? What do you think should go in the else?

2021-10-29 04:43 UTC, dstathis commented on src/charm.py
> +        if not self.model.relations["monitoring"] and self._container.can_connect():
1. There may be multiple instances of the relation. One breaking should not cause us to disable metrics.
2. Can anyone confirm this? If so is it not a bug?

2021-10-29 04:47 UTC, dstathis commented on src/charm.py
> +    def _hostname(self, unit_number: Optional[int] = None) -> str:
Done.

2021-10-29 04:50 UTC, dstathis commented on src/charm.py
> +        seeds_list = [self._hostname(unit_number=x) for x in [0, 1, 2]][: self._goal_units()]
I don't think this change is needed. The existing comment is more explicit. Also I feel my list comprehension is easier to understand (I'm sure this point is completely subjective).

2021-10-29 04:53 UTC, dstathis commented on src/charm.py
> +                    raise
It works for now. I am going to give this method a lot more attention in the next PR as I think it needs a bit of an overhaul.

2021-10-29 04:54 UTC, dstathis commented on tox.ini
> +    pep8-naming
Nothing calls it. I'll probably just copy the whole linting config from one of your repos at some point in the future. For now it is already a lot.

2021-10-29 11:31 UTC, simonaronsson requested changes
Looks good overall, but there are some issues I think you should address prior to merging.

2021-10-29 11:31 UTC, simonaronsson commented on CONTRIBUTING.md
> +  [Canonical Mattermost public channel](https://chat.charmhub.io/charmhub/channels/charm-dev)
```suggestion
  [the CharmHub Mattermost server](https://chat.charmhub.io/charmhub/channels/charm-dev)
```

2021-10-29 11:31 UTC, simonaronsson commented on src/cassandra_server.py
> +                    f"CREATE ROLE IF NOT EXISTS '{username}' WITH PASSWORD = '{password}' AND LOGIN = true"
This is not a recommended way to do SQL queries. While the blast radius might be non-existant in this case, you should still make sure to do safe query parameterization to not open up for injections. f-strings unfortunately are just as susceptible as string formats.

2021-10-29 11:31 UTC, simonaronsson commented on src/cassandra_server.py
> +                conn.execute(f"GRANT ALL PERMISSIONS ON KEYSPACE {db_name} to '{user}'")
Same comment as above

2021-10-29 11:31 UTC, simonaronsson commented on src/cassandra_server.py
> +                    f"CREATE ROLE {ROOT_USER} WITH PASSWORD = '{root_pass_secondary}' AND SUPERUSER = true AND LOGIN = true",
Same here. Injection vector

2021-10-29 11:31 UTC, simonaronsson commented on src/cassandra_server.py
> +                    (random_password,),
Much better 👏🏽

2021-11-05 09:29 UTC, simskij approved these changes

2021-11-05 16:12 UTC, merged