Tests infrastructure and a minor improvement
canonical/cassandra-k8s-operator pull request #7
Opened 2021-05-13 21:38 UTC by dstathis

2021-05-14 02:43 UTC, rbarry82 approved these changes
Looks great

2021-05-14 02:43 UTC, rbarry82 commented on src/charm.py
> +        if services != layer["services"]:
A+ simplification

2021-05-14 12:58 UTC, sed-i commented on .coveragerc
> +omit = lib/charms/cassandra/v1/relation.py
you wouldn't need this file if instead of `ops>=1.2` you'd have `git+https://github.com/balbirthomas/operator/@provider-consumer-lib#egg=ops` in `requirements.txt`

2021-05-14 13:01 UTC, sed-i commented on src/charm.py
> +        if services != layer["services"]:
^ this :)
you can simplify further: `services = container.get_plan().get("services")` - None would still compare nicely

2021-05-17 19:17 UTC, dstathis commented on .coveragerc
> +omit = lib/charms/cassandra/v1/relation.py
I prefer to do it this way in case there are breaking changes to relation.py

2021-05-18 17:02 UTC, balbirthomas requested changes

2021-05-18 17:02 UTC, balbirthomas commented on .coveragerc
> +omit = lib/charms/cassandra/v1/relation.py
Would it be a reasonable to expect that charms that depend on provider consumer library will be updated if a breaking change is announced, of which there has only been one to date. Besides using the latest library ensures it is regularly put through it's paces and tested. Feel free to ping me whenever you want it rebased onto latest master, which I do regularly.

2021-05-18 17:02 UTC, balbirthomas commented on .github/workflows/run_tests.yaml
> +name: Run-Tests
+1 Good idea.

2021-05-18 17:02 UTC, balbirthomas commented on tests/test_charm.py
> +@patch.object(ops.model.Container, "pull", new=fake_pull)
Not a huge fan of this much patching. But oh well. Each to his own. No changes requested here. Just an observation.

2021-05-18 17:08 UTC, Abuelodelanada approved these changes
Looks good to me.
I don't have much more to say than what Balbir and Leon have already said.

2021-05-18 17:16 UTC, dstathis commented on .coveragerc
> +omit = lib/charms/cassandra/v1/relation.py
I was under the assumption that this would be in ops at some point. At that point, I will just switch to using that version. I see no benefit to pointing at an edge ops version.

2021-05-18 17:18 UTC, dstathis commented on .coveragerc
> +omit = lib/charms/cassandra/v1/relation.py
Also, I don't think it is reasonable to just break charms without warning. Once this is in ops I would expect the interface to be stable unless ops gets a major version increase.

2021-05-18 17:19 UTC, dstathis commented on tests/test_charm.py
> +@patch.object(ops.model.Container, "pull", new=fake_pull)
I would love to patch less but none of these are implemented in harness so what else can I do?

2021-05-18 17:24 UTC, balbirthomas commented on tests/test_charm.py
> +@patch.object(ops.model.Container, "pull", new=fake_pull)
I am not requesting changes here. It is certainly a valid way to do it.

2021-05-18 17:26 UTC, balbirthomas commented on .coveragerc
> +omit = lib/charms/cassandra/v1/relation.py
I disagree on this, but I will remove the request on changes to unblock you. I would like to suggest you double check with @jlounder what his preferences are. Perhaps point out my own view is that our charms should be using and testing the latest provider consumer library, which I keep rebased against the latest master of operator framework, so that any issues are detected.

2021-05-18 17:26 UTC, balbirthomas approved these changes

2021-05-18 17:28 UTC, merged